source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-bookshop"
  gem "cloudcannon-jekyll-bookshop"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-tagging'
  gem "jekyll-sitemap"
  gem "jekyll-pagebreak"
  gem "webrick"
end
